test_that("Gra przyjmuje nazwe funkcji strategii i zwraca liste zawierajaca macierz gry i dlugosc trwania gry",{
  warunki <- c("krolik"=3,"owca"=1,"swinia"=0,"krowa"=0,"kon"=0,"maly_pies"=0,"duzy_pies"=0)
  expect_error(gra())
  expect_error(gra(strategia_owce()))
  expect_is(gra(strategia_wymian_0_0_0_0),"list")
  expect_length(gra(strategia_wymian_0_0_0_0),2)
  expect_named(gra(strategia_wymian_0_0_0_0),NULL)
  expect_length(gra(strategia_wymian_1_1_1_1),2)
  expect_is(gra(strategia_wymian_1_1_1_1),"list")
  expect_named(gra(strategia_wymian_1_1_1_1),NULL)
  expect_length(gra(strategia_owce),2)
  expect_is(gra(strategia_owce),"list")
  expect_named(gra(strategia_owce),NULL)
  expect_is(gra(strategia_owce,warunek_wygranej = warunki),"list")
})
